Repository LikeMindsCommunity/likeminds-chat-android-community-archV1, pull requests merged in 2024-12, with the labels that each got.

#63 [Hotfix/LM-13129] Invalid JSON Object Widget Metadata
  chatmm/dependencies.gradle
  lm-chat-root-dependencies.gradle
Labels: hotfix

#65 [LM-13245] Issues reported by choice
  app/src/main/java/com/likeminds/chatsampleapp/ChatMMessagingService.kt
  app/src/main/java/com/likeminds/chatsampleapp/auth/view/AfterLoginActivity.kt
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCore.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/DMFeedFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/SendDMRequestDialogFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/adapter/DMAdapter.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/viewmodel/DMFeedViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/homefeed/util/HomeFeedPreferences.kt
  chatmm/src/main/java/com/likeminds/chatmm/homefeed/viewmodel/HomeFeedViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/theme/customview/LikeMindsTextView.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/permissions/LMChatPermission.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/sharedpreferences/LMChatMasterPrefUtils.kt
  chatmm/src/main/res/layout/fragment_chatroom_detail.xml
  chatmm/src/main/res/values/strings.xml
Labels: bug, enhancement

#66 Release v2.7.0
  app/src/main/java/com/likeminds/chatsampleapp/ChatMMessagingService.kt
  app/src/main/java/com/likeminds/chatsampleapp/auth/view/AfterLoginActivity.kt
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCore.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/DMFeedFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/SendDMRequestDialogFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/adapter/DMAdapter.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/viewmodel/DMFeedViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/homefeed/util/HomeFeedPreferences.kt
  chatmm/src/main/java/com/likeminds/chatmm/homefeed/viewmodel/HomeFeedViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/theme/customview/LikeMindsTextView.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/permissions/LMChatPermission.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/sharedpreferences/LMChatMasterPrefUtils.kt
  chatmm/src/main/res/layout/fragment_chatroom_detail.xml
  chatmm/src/main/res/values/strings.xml
Labels: release

#68 [Hotfix][LM-13261] Fixed: Crash on receiving notifications
  chatmm/dependencies.gradle
  lm-chat-root-dependencies.gradle
Labels: hotfix
