Repository LikeMindsCommunity/likeminds-chat-android-community-archV1, pull requests merged in 2024-10, with the labels that each got.

#55 [Hotfix][LM-12900] M2CM not working
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  lm-chat-root-dependencies.gradle
Labels: hotfix

#56 Release v2.5.0
  app/src/main/res/values/strings.xml
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/LMChatAttachmentPickerItemViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/LMChatAttachmentType.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/LMChatConversationProgressViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomConversationItemViewDataBinderUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/adapter/ChatroomDetailAdapter.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/adapter/LMChatAttachmentBarAdapter.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/adapter/databinder/LMChatAttachmentPickerItemViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/view/adapter/databinder/ConversationProgressViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/DMFeedFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/model/MediaExtras.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/util/LMVoiceRecorder.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/view/ConversationMediaEditFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/member/model/MemberViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ViewDataConverter.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/worker/ConversationMediaUploadWorker.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/worker/MediaUploadWorker.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/worker/UploadHelper.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/membertagging/view/MemberTaggingView.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/model/ViewType.kt
  chatmm/src/main/res/.DS_Store
  chatmm/src/main/res/layout/fragment_chatroom_detail.xml
  chatmm/src/main/res/layout/fragment_conversation_media_edit.xml
  chatmm/src/main/res/layout/item_conversation.xml
  chatmm/src/main/res/layout/item_conversation_audio.xml
  chatmm/src/main/res/layout/item_conversation_custom_widget.xml
  chatmm/src/main/res/layout/item_conversation_link.xml
  chatmm/src/main/res/layout/item_conversation_multiple_document.xml
  chatmm/src/main/res/layout/item_conversation_multiple_media.xml
  chatmm/src/main/res/layout/item_conversation_poll.xml
  chatmm/src/main/res/layout/item_conversation_single_gif.xml
  chatmm/src/main/res/layout/item_conversation_single_image.xml
  chatmm/src/main/res/layout/item_conversation_single_pdf.xml
  chatmm/src/main/res/layout/item_conversation_single_video.xml
  chatmm/src/main/res/layout/item_conversation_voice_note.xml
  chatmm/src/main/res/layout/layout_bottom_bar_attachments.xml
  chatmm/src/main/res/layout/lm_chat_item_conversation_progress.xml
  chatmm/src/main/res/layout/lm_chat_item_picker_attachment.xml
  chatmm/src/main/res/values/strings.xml
  lm-chat-root-dependencies.gradle
Labels: release

#57 Release/v2.6.0 Product Signoff Bugs
  app/.DS_Store
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/ChatroomDetailExtras.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomConversationItemViewDataBinderUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/pushnotification/util/LMChatNotificationHandler.kt
  chatmm/src/main/java/com/likeminds/chatmm/pushnotification/util/NotificationActionBroadcastReceiver.kt
  chatmm/src/main/java/com/likeminds/chatmm/search/view/adapter/databinder/SearchConversationViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/search/viewmodel/SearchViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/Route.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ViewDataConverter.kt
  chatmm/src/main/res/values/strings.xml
Labels: bug

#58 Release/v2.6.0
  app/.DS_Store
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/ChatroomDetailExtras.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomConversationItemViewDataBinderUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/explore/view/ChatroomExploreFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/AttachmentMetaViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/AttachmentViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/DMFeedFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/homefeed/view/HomeFeedFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/member/model/MemberViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/member/model/SDKClientInfoViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/pushnotification/model/ChatroomNotificationViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/pushnotification/util/LMChatNotificationHandler.kt
  chatmm/src/main/java/com/likeminds/chatmm/pushnotification/util/NotificationActionBroadcastReceiver.kt
  chatmm/src/main/java/com/likeminds/chatmm/pushnotification/util/NotificationUtils.kt
  chatmm/src/main/java/com/likeminds/chatmm/pushnotification/viewmodel/LMNotificationViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/search/model/LMChatSearchExtras.kt
  chatmm/src/main/java/com/likeminds/chatmm/search/model/LMChatSearchResult.kt
  chatmm/src/main/java/com/likeminds/chatmm/search/view/LMChatSearchActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/search/view/LMChatSearchFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/search/view/adapter/databinder/SearchConversationViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/search/viewmodel/SearchViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/Route.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/TimeUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ViewDataConverter.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/user/LMChatUserMetaData.kt
  chatmm/src/main/res/layout/lm_chat_activity_search.xml
  chatmm/src/main/res/menu/lm_chat_chatroom_menu.xml
  chatmm/src/main/res/values/strings.xml
  lm-chat-root-dependencies.gradle
Labels: enhancement

#59 [Hotfix][LM-12953] Fixed crash on Member Directory Search
  chatmm/dependencies.gradle
  lm-chat-root-dependencies.gradle
Labels: bug
