Repository LikeMindsCommunity/likeminds-chat-android-community-archV1, pull requests merged in 2024-08, with the labels that each got.

#41 [Hotfix] [LM-12600] Downgraded Kotlin Version and other library versions
  app/src/main/java/com/likeminds/chatsampleapp/auth/view/AfterLoginActivity.kt
  build.gradle
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/view/adapter/databinder/ConversationSingleGifItemViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/view/LMChatMediaPickerDocumentFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/view/LMChatMediaPickerFolderFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/view/LMChatMediaPickerItemFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/member/view/LMChatCommunityMembersFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ExtrasUtil.kt
  chatmm/src/main/res/layout/lm_chat_fragment_community_members.xml
  lm-chat-root-dependencies.gradle
Labels: bug

#43 [LM-12665] Choice Connect Chat Bugs
  .DS_Store
  app/src/main/java/com/likeminds/chatsampleapp/ChatMMApplication.kt
  app/src/main/java/com/likeminds/chatsampleapp/auth/view/AuthActivity.kt
  chatmm/dependencies.gradle
  chatmm/src/main/AndroidManifest.xml
  chatmm/src/main/java/com/likeminds/chatmm/chat/view/LMChatFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ViewParticipantsFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/di/search/SearchComponent.kt
  chatmm/src/main/java/com/likeminds/chatmm/homefeed/view/HomeFeedFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/view/LMChatMediaPickerDocumentFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/view/MediaPickerAudioFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/member/view/LMChatCommunityMembersFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/search/util/LMChatCustomSearchBar.kt
  chatmm/src/main/java/com/likeminds/chatmm/search/view/LMChatSearchActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/search/view/LMChatSearchFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/theme/model/LMFonts.kt
  chatmm/src/main/java/com/likeminds/chatmm/theme/util/ThemeUtil.kt
  chatmm/src/main/res/layout/activity_search.xml
  chatmm/src/main/res/layout/fragment_media_picker_audio.xml
  chatmm/src/main/res/layout/fragment_view_participants.xml
  chatmm/src/main/res/layout/lm_chat_activity_search.xml
  chatmm/src/main/res/layout/lm_chat_fragment_community_members.xml
  chatmm/src/main/res/layout/lm_chat_fragment_media_picker_document.xml
  chatmm/src/main/res/layout/lm_chat_fragment_search.xml
  chatmm/src/main/res/layout/lm_chat_layout_search_bar.xml
  chatmm/src/main/res/navigation/lm_chat_nav_search.xml
  chatmm/src/main/res/values/dimens.xml
  lm-chat-root-dependencies.gradle
Labels: bug

#44 Added Realtime Listener in DM Feed
  chatmm/src/main/java/com/likeminds/chatmm/chat/view/LMChatFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/DMFeedFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/viewmodel/DMFeedViewModel.kt
  lm-chat-root-dependencies.gradle
Labels: bug

#47 [Hotfix][LM12715] Handle crash on logout()
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/likeminds/chatsampleapp/ChatMMApplication.kt
  app/src/main/java/com/likeminds/chatsampleapp/auth/view/AfterLoginActivity.kt
  app/src/main/java/com/likeminds/chatsampleapp/likemindschat/LikeMindsChatActivity.kt
  app/src/main/res/layout/activity_after_login.xml
  app/src/main/res/layout/activity_likeminds_chat.xml
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCore.kt
  chatmm/src/main/java/com/likeminds/chatmm/SDKApplication.kt
  chatmm/src/main/res/.DS_Store
Labels: bug

#46 [LM-12707] Added checks for opened chatroom in notification receiving
  app/src/main/java/com/likeminds/chatsampleapp/ChatMMApplication.kt
  chatmm/src/main/java/com/likeminds/chatmm/SDKApplication.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/pushnotification/util/LMChatNotificationHandler.kt
  lm-chat-root-dependencies.gradle
Labels: enhancement

#48 Release v2.4.0
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/likeminds/chatsampleapp/ChatMMApplication.kt
  app/src/main/java/com/likeminds/chatsampleapp/auth/view/AfterLoginActivity.kt
  app/src/main/java/com/likeminds/chatsampleapp/likemindschat/LikeMindsChatActivity.kt
  app/src/main/res/layout/activity_after_login.xml
  app/src/main/res/layout/activity_likeminds_chat.xml
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCore.kt
  chatmm/src/main/java/com/likeminds/chatmm/SDKApplication.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/pushnotification/util/LMChatNotificationHandler.kt
  chatmm/src/main/res/.DS_Store
  lm-chat-root-dependencies.gradle
Labels: release
