Repository LikeMindsCommunity/likeminds-chat-android-community-archV1, pull requests merged in 2025-05, with the labels that each got.

#100 [Hotfix] [LM-13717] Added check for deleted chatroom in notification stack
  chatmm/dependencies.gradle
  lm-chat-root-dependencies.gradle
Labels: hotfix

#101 [Hotfix][LM-13717] Added check for deleted chatroom in notification stack
  chatmm/dependencies.gradle
  lm-chat-root-dependencies.gradle
Labels: hotfix

#99 [LM-13610] Share Messages
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCoreCallback.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/ChatroomDetailActionModeData.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/Route.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ShareUtils.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/worker/ConversationWorker.kt
  chatmm/src/main/res/menu/lm_chat_message_actions_menu.xml
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/CommunityHybridChatApplication.kt
  lm-chat-root-dependencies.gradle
Labels: enhancement

#102 Release/v2.14.0
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCoreCallback.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/ChatroomDetailActionModeData.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/Route.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ShareUtils.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/worker/ConversationWorker.kt
  chatmm/src/main/res/menu/lm_chat_message_actions_menu.xml
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/CommunityHybridChatApplication.kt
  lm-chat-root-dependencies.gradle
Labels: enhancement

#105 [LM-13746] Fixed Back Press on Shared Message Closes the App
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCore.kt
  chatmm/src/main/java/com/likeminds/chatmm/SDKApplication.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/Route.kt
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/CommunityHybridChatApplication.kt
Labels: bug

#108 Release/v2.15.0
  ai-chatbot/src/main/AndroidManifest.xml
  ai-chatbot/src/main/java/com/likeminds/ai/chatbot/AIChatbotActivity.kt
  ai-chatbot/src/main/java/com/likeminds/ai/chatbot/auth/view/AfterLoginActivity.kt
  ai-chatbot/src/main/java/com/likeminds/ai/chatbot/auth/view/AuthActivity.kt
  build.gradle
  chatmm/src/main/AndroidManifest.xml
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCore.kt
  chatmm/src/main/java/com/likeminds/chatmm/SDKApplication.kt
  chatmm/src/main/java/com/likeminds/chatmm/aichatbot/view/LMChatAIBotInitiationActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ViewParticipantsActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/explore/view/ChatroomExploreActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/view/LMChatMediaPickerActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/view/MediaActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/member/view/LMChatCommunityMembersActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/report/view/ReportActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/search/view/LMChatSearchActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/Route.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/customview/BaseAppCompatActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/membertagging/MemberTaggingDecoder.kt
  community-chat/src/main/java/com/likeminds/community/chat/CommunityChatActivity.kt
  community-chat/src/main/java/com/likeminds/community/chat/auth/view/AfterLoginActivity.kt
  community-chat/src/main/java/com/likeminds/community/chat/auth/view/AuthActivity.kt
  community-hybrid-chat/src/main/AndroidManifest.xml
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/CommunityHybridChatActivity.kt
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/CommunityHybridChatApplication.kt
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/auth/view/AfterLoginActivity.kt
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/auth/view/AuthActivity.kt
  gradle/wrapper/gradle-wrapper.properties
  lm-chat-root-dependencies.gradle
  networking-chat/src/main/AndroidManifest.xml
  networking-chat/src/main/java/com/likeminds/networking/chat/NetworkingChatActivity.kt
  networking-chat/src/main/java/com/likeminds/networking/chat/auth/view/AfterLoginActivity.kt
  networking-chat/src/main/java/com/likeminds/networking/chat/auth/view/AuthActivity.kt
Labels: enhancement
