Repository LikeMindsCommunity/likeminds-chat-android-community-archV1, pull requests merged in 2025-03, with the labels that each got.

#83 [LM-13391] Added Filter State Message
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCore.kt
  chatmm/src/main/java/com/likeminds/chatmm/SDKApplication.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/ConversationState.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/ConversationViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/util/ChatReplyUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/view/adapter/databinder/ConversationActionItemViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/adapter/databinder/DMChatroomViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ViewDataConverter.kt
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/CommunityHybridChatApplication.kt
Labels: enhancement

#85 [LM-12407] retry mechanism
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomConversationItemViewDataBinderUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/AttachmentViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/ConversationViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ViewDataConverter.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/model/GenericFileRequest.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/worker/ConversationMediaUploadWorker.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/worker/ConversationWorker.kt
Labels: enhancement

#84 Release v2.11.0
  chatmm/build.gradle
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCore.kt
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCoreCallback.kt
  chatmm/src/main/java/com/likeminds/chatmm/SDKApplication.kt
  chatmm/src/main/java/com/likeminds/chatmm/chat/view/CommunityHybridChatFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomConversationItemViewDataBinderUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/VoiceNoteUtils.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/AttachmentViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/ConversationState.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/ConversationViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/util/ChatReplyUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/view/adapter/databinder/ConversationActionItemViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/view/adapter/databinder/ConversationPollItemViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/ApproveDMRequestDialogFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/RejectDMRequestDialogFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/SendDMRequestDialogFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/adapter/databinder/DMChatroomViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/homefeed/view/ChatroomInviteDialogFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/homefeed/viewmodel/CommunityChatViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/MediaRepository.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/customviews/TimeLineView.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/customviews/VideoTrimmer.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/util/LMMediaPlayer.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/util/LMVoiceRecorder.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/util/MediaUtils.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/util/Mp4Cutter.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/view/MediaPickerAudioFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/polls/view/AddPollOptionDialog.kt
  chatmm/src/main/java/com/likeminds/chatmm/pushnotification/util/NotificationUtils.kt
  chatmm/src/main/java/com/likeminds/chatmm/reactions/view/ReactionListFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/reactions/view/ReactionsListDialog.kt
  chatmm/src/main/java/com/likeminds/chatmm/theme/customview/edittext/LikeMindsEmojiEditText.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/AndroidUtils.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/Route.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ValueUtils.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ViewDataConverter.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/chrometabs/CustomTabHelper.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/chrometabs/CustomTabIntent.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/chrometabs/CustomTabUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/connectivity/ConnectivityBroadcastReceiver.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/customview/BaseBottomSheetFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/databinding/BlurTransformation.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/downloader/DownloadUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/downloader/MediaDownloadWorker.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/file/util/ContentUriUtils.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/file/util/FileUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/model/GenericFileRequest.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/utils/FileHelper.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/worker/ConversationMediaUploadWorker.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/worker/ConversationWorker.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/membertagging/MemberTaggingDecoder.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/membertagging/util/MemberTaggingClickableSpan.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/membertagging/util/MemberTaggingTextWatcher.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/user/LMChatUserMetaData.kt
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/CommunityHybridChatApplication.kt
  lm-chat-root-dependencies.gradle
Labels: release

#87 Release/v5.3.0
  chatmm/build.gradle
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCore.kt
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCoreCallback.kt
  chatmm/src/main/java/com/likeminds/chatmm/SDKApplication.kt
  chatmm/src/main/java/com/likeminds/chatmm/chat/view/CommunityHybridChatFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomConversationItemViewDataBinderUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/VoiceNoteUtils.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/AttachmentViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/ConversationState.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/ConversationViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/util/ChatReplyUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/view/adapter/databinder/ConversationActionItemViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/view/adapter/databinder/ConversationPollItemViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/ApproveDMRequestDialogFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/RejectDMRequestDialogFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/SendDMRequestDialogFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/adapter/databinder/DMChatroomViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/homefeed/view/ChatroomInviteDialogFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/homefeed/viewmodel/CommunityChatViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/MediaRepository.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/customviews/TimeLineView.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/customviews/VideoTrimmer.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/util/LMMediaPlayer.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/util/LMVoiceRecorder.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/util/MediaUtils.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/util/Mp4Cutter.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/view/MediaPickerAudioFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/polls/view/AddPollOptionDialog.kt
  chatmm/src/main/java/com/likeminds/chatmm/pushnotification/util/NotificationUtils.kt
  chatmm/src/main/java/com/likeminds/chatmm/reactions/view/ReactionListFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/reactions/view/ReactionsListDialog.kt
  chatmm/src/main/java/com/likeminds/chatmm/theme/customview/edittext/LikeMindsEmojiEditText.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/AndroidUtils.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/Route.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ValueUtils.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ViewDataConverter.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/chrometabs/CustomTabHelper.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/chrometabs/CustomTabIntent.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/chrometabs/CustomTabUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/connectivity/ConnectivityBroadcastReceiver.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/customview/BaseBottomSheetFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/databinding/BlurTransformation.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/downloader/DownloadUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/downloader/MediaDownloadWorker.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/file/util/ContentUriUtils.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/file/util/FileUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/model/GenericFileRequest.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/utils/FileHelper.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/worker/ConversationMediaUploadWorker.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/worker/ConversationWorker.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/membertagging/MemberTaggingDecoder.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/membertagging/util/MemberTaggingClickableSpan.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/membertagging/util/MemberTaggingTextWatcher.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/user/LMChatUserMetaData.kt
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/CommunityHybridChatApplication.kt
  lm-chat-root-dependencies.gradle
Labels: enhancement

#88 [Hotfix] Fixed Compile Error and Disabled Edge-to-Edge
  ai-chatbot/src/main/AndroidManifest.xml
  ai-chatbot/src/main/java/com/likeminds/ai/chatbot/AIChatbotActivity.kt
  ai-chatbot/src/main/java/com/likeminds/ai/chatbot/auth/view/AfterLoginActivity.kt
  ai-chatbot/src/main/java/com/likeminds/ai/chatbot/auth/view/AuthActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/aichatbot/view/LMChatAIBotInitiationActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ViewParticipantsActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/explore/view/ChatroomExploreActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/util/ChatReplyUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/view/LMChatMediaPickerActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/media/view/MediaActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/member/view/LMChatCommunityMembersActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/report/view/ReportActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/search/view/LMChatSearchActivity.kt
  chatmm/src/main/res/values-v35/values.xml
  chatmm/src/main/res/values/values.xml
  community-chat/src/main/java/com/likeminds/community/chat/CommunityChatActivity.kt
  community-chat/src/main/java/com/likeminds/community/chat/auth/view/AfterLoginActivity.kt
  community-chat/src/main/java/com/likeminds/community/chat/auth/view/AuthActivity.kt
  community-hybrid-chat/src/main/AndroidManifest.xml
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/CommunityHybridChatActivity.kt
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/auth/view/AfterLoginActivity.kt
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/auth/view/AuthActivity.kt
  lm-chat-root-dependencies.gradle
  networking-chat/src/main/AndroidManifest.xml
  networking-chat/src/main/java/com/likeminds/networking/chat/NetworkingChatActivity.kt
  networking-chat/src/main/java/com/likeminds/networking/chat/auth/view/AfterLoginActivity.kt
  networking-chat/src/main/java/com/likeminds/networking/chat/auth/view/AuthActivity.kt
Labels: hotfix

#90 [LM-13552] Added Util function for Create or Get Util Function
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/dm/util/LMChatDMUtil.kt
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/auth/view/AfterLoginActivity.kt
Labels: enhancement

#92 [LM-13556] Fixed crash for NotificationClient
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCore.kt
  chatmm/src/main/java/com/likeminds/chatmm/SDKApplication.kt
  chatmm/src/main/java/com/likeminds/chatmm/homefeed/view/CommunityChatFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/pushnotification/viewmodel/LMNotificationViewModel.kt
Labels: bug

#91 Release v2.12.0
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCore.kt
  chatmm/src/main/java/com/likeminds/chatmm/SDKApplication.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/util/LMChatDMUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/homefeed/view/CommunityChatFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/pushnotification/viewmodel/LMNotificationViewModel.kt
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/auth/view/AfterLoginActivity.kt
  lm-chat-root-dependencies.gradle
Labels: release

#93 Release v5.4.0
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/LMChatCore.kt
  chatmm/src/main/java/com/likeminds/chatmm/SDKApplication.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/util/LMChatDMUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/homefeed/view/CommunityChatFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/pushnotification/viewmodel/LMNotificationViewModel.kt
  community-hybrid-chat/src/main/java/com/likeminds/community/hybrid/chat/auth/view/AfterLoginActivity.kt
  lm-chat-root-dependencies.gradle
Labels: release

#94 [LM-13382] Reply Privately
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/LMAnalytics.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/ChatReplyViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/ChatroomDetailActionModeData.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/ChatroomDetailExtras.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/LMChatReplyPrivatelyExtras.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomConversationItemViewDataBinderUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/adapter/ChatroomDetailAdapter.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/AttachmentViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/util/ChatReplyUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/view/adapter/databinder/ConversationWidgetItemViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/SendDMRequestDialogFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/SDKPreferences.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ViewDataConverter.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/worker/ConversationWorker.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/user/LMChatUserMetaData.kt
  chatmm/src/main/java/com/likeminds/chatmm/widget/model/LMMetaViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/widget/model/WidgetViewData.kt
  chatmm/src/main/res/layout/layout_chat_reply.xml
  chatmm/src/main/res/layout/layout_reply.xml
  chatmm/src/main/res/menu/lm_chat_message_actions_menu.xml
  chatmm/src/main/res/values/strings.xml
Labels: enhancement
