Repository LikeMindsCommunity/likeminds-chat-android-community-archV1, pull requests merged in 2025-04, with the labels that each got.

#95 [LM-13382] Reply Privately Peer Testing
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/ChatReplyViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomConversationItemViewDataBinderUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/ConversationViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/theme/model/LMChatAppearance.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ViewDataConverter.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/worker/ConversationWorker.kt
  chatmm/src/main/java/com/likeminds/chatmm/widget/model/LMMetaViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/widget/model/WidgetViewData.kt
  chatmm/src/main/res/layout/layout_chat_reply.xml
  chatmm/src/main/res/layout/layout_reply.xml
  lm-chat-root-dependencies.gradle
Labels: bug

#96 Release v2.13.0
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/LMAnalytics.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/ChatReplyViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/ChatroomDetailActionModeData.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/ChatroomDetailExtras.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/LMChatReplyPrivatelyExtras.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomConversationItemViewDataBinderUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/adapter/ChatroomDetailAdapter.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/AttachmentViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/ConversationViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/util/ChatReplyUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/view/adapter/databinder/ConversationWidgetItemViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/SendDMRequestDialogFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/theme/model/LMChatAppearance.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/SDKPreferences.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ViewDataConverter.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/worker/ConversationWorker.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/user/LMChatUserMetaData.kt
  chatmm/src/main/java/com/likeminds/chatmm/widget/model/LMMetaViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/widget/model/WidgetViewData.kt
  chatmm/src/main/res/layout/layout_chat_reply.xml
  chatmm/src/main/res/layout/layout_reply.xml
  chatmm/src/main/res/menu/lm_chat_message_actions_menu.xml
  chatmm/src/main/res/values/strings.xml
  lm-chat-root-dependencies.gradle
Labels: release

#98 Release v5.5.0
  chatmm/dependencies.gradle
  chatmm/src/main/java/com/likeminds/chatmm/LMAnalytics.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/ChatReplyViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/ChatroomDetailActionModeData.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/ChatroomDetailExtras.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/model/LMChatReplyPrivatelyExtras.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/util/ChatroomConversationItemViewDataBinderUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailActivity.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/ChatroomDetailFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/view/adapter/ChatroomDetailAdapter.kt
  chatmm/src/main/java/com/likeminds/chatmm/chatroom/detail/viewmodel/ChatroomDetailViewModel.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/AttachmentViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/model/ConversationViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/util/ChatReplyUtil.kt
  chatmm/src/main/java/com/likeminds/chatmm/conversation/view/adapter/databinder/ConversationWidgetItemViewDataBinder.kt
  chatmm/src/main/java/com/likeminds/chatmm/dm/view/SendDMRequestDialogFragment.kt
  chatmm/src/main/java/com/likeminds/chatmm/theme/model/LMChatAppearance.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/SDKPreferences.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/ViewDataConverter.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/mediauploader/worker/ConversationWorker.kt
  chatmm/src/main/java/com/likeminds/chatmm/utils/user/LMChatUserMetaData.kt
  chatmm/src/main/java/com/likeminds/chatmm/widget/model/LMMetaViewData.kt
  chatmm/src/main/java/com/likeminds/chatmm/widget/model/WidgetViewData.kt
  chatmm/src/main/res/layout/layout_chat_reply.xml
  chatmm/src/main/res/layout/layout_reply.xml
  chatmm/src/main/res/menu/lm_chat_message_actions_menu.xml
  chatmm/src/main/res/values/strings.xml
  lm-chat-root-dependencies.gradle
Labels: enhancement
